# Generated by Django 4.2.25 on 2025-10-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCStationaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measure')),
                ('amount_per_box_pack_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('full_boxes_packs_rolls', models.PositiveIntegerField(default=0)),
                ('open', models.PositiveIntegerField(default=0)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stationary_images/')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
