# Generated by Django 4.2.25 on 2025-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measure')),
                ('amount_per_box_pack_roll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_boxes_packs_rolls', models.PositiveIntegerField(default=0)),
                ('open', models.PositiveIntegerField(default=0)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='consumable_images/')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_loc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Block A (Consumable Items)',
                'ordering': ['sr_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='blockcstationaryitem',
            options={'ordering': ['sr_no'], 'verbose_name_plural': 'Block C (Stationary Items)'},
        ),
        migrations.AddField(
            model_name='blockcstationaryitem',
            name='dispatch_loc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blockcstationaryitem',
            name='person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
