# Generated by Django 4.2.25 on 2025-11-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_blockaconsumableitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(max_length=50)),
                ('amount_per_pack', models.IntegerField(blank=True, null=True)),
                ('full_boxes', models.IntegerField(blank=True, null=True)),
                ('open_packs', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Misc Items',
                'ordering': ['sr_no'],
            },
        ),
    ]
