# Generated by Django 4.2.25 on 2025-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_miscitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miscitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='miscitem',
            name='amount_per_pack',
        ),
        migrations.RemoveField(
            model_name='miscitem',
            name='full_boxes',
        ),
        migrations.RemoveField(
            model_name='miscitem',
            name='open_packs',
        ),
        migrations.AddField(
            model_name='miscitem',
            name='amount_per_box_pack_roll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miscitem',
            name='dispatch_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='miscitem',
            name='full_boxes_packs_rolls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miscitem',
            name='open',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miscitem',
            name='person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='misc_images/'),
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='in_stock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='sr_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
