# Generated by Django 4.2.25 on 2025-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_miscitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_per_box_pack_roll', models.FloatField(blank=True, null=True)),
                ('full_boxes_packs_rolls', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('in_stock', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='consumables/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Consumables',
                'ordering': ['sr_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='miscitem',
            options={'ordering': ['sr_no'], 'verbose_name_plural': 'Misc items'},
        ),
    ]
