# Generated by Django 4.2.25 on 2025-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_ppes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(blank=True, max_length=20, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_per_box_pack_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('full_boxes_packs_rolls', models.CharField(blank=True, max_length=50, null=True)),
                ('open', models.CharField(blank=True, max_length=50, null=True)),
                ('in_stock', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ppes_images/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Block D (Spare Items)',
                'ordering': ['sr_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='fixedassets',
            options={'ordering': ['sr_no'], 'verbose_name_plural': 'Block B (Fixed Assets)'},
        ),
    ]
