# Generated by Django 4.2.25 on 2025-11-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_spareitems_alter_fixedassets_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(blank=True, max_length=20, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_mentioned', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ppes_images/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Block E (Keys)',
                'ordering': ['sr_no'],
            },
        ),
    ]
