# Generated by Django 4.2.25 on 2025-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_teaitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaitems',
            name='old_stock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
