# Generated by Django 4.2.25 on 2025-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_blockaconsumableitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=20)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('register_page_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tools_and_spares', models.CharField(blank=True, max_length=255, null=True)),
                ('cabinet_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rack_no', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('store_stock', models.CharField(blank=True, max_length=50, null=True)),
                ('column4', models.CharField(blank=True, max_length=255, null=True)),
                ('column3', models.CharField(blank=True, max_length=255, null=True)),
                ('column2', models.CharField(blank=True, max_length=255, null=True)),
                ('column1', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tea_items_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store Inspection Checklist (ThirdRail)',
                'ordering': ['sr_no'],
            },
        ),
    ]
