# Generated by Django 4.2.25 on 2025-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_thirdrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedassets',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keys',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miscitem',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ppes',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spareitems',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teaitems',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thirdrail',
            name='sr_no',
            field=models.IntegerField(),
        ),
    ]
